@startuml 大原情報科学大学・図書館システムドメインモデル図
skinparam componentStyle rectangle
[会員] o-- [会員番号]
[会員] o-- [借りている図書]
[会員] o-- [メールアドレス]
[会員] <|-- [学生]
[会員] <|-- [教職員]

[学生] o-- [雑誌を借りられない制約]
[学生] o-- [上限冊数6冊]
[学生] o-- [学生証]
[学生] o-- [学生番号]

[教職員] o-- [上限冊数12冊]
[教職員] o-- [職員証]
[教職員] o-- [職員番号]

[事務職員] o-- [メールアドレス]

[図書] o-- [管理番号]
[図書] o-- [貸出期間]
[図書] o-- [貸出履歴]
[図書] <|-- [書籍]
[図書] <|-- [雑誌]

[図書館システム] o-- [予約カード]

@enduml