@startuml .

class Robodog {
  - 名前
  - 時刻
  ' 挨拶はdictで管理
  - 挨拶
  - 1つ目の整数
  - 2つ目の整数
  - 足し算の結果

  + 名前を変更する()
  + 名前を取得する()
  + 時刻に応じた取得する()
  + 挨拶を取得する()
  + 1つ目の整数を登録する()
  + 2つ目の整数を登録する()
  + 1つ目の整数を取得する()
  + 2つ目の整数を取得する()
  + 2つの整数を足し算する()
  + 2つの整数の足し算結果を登録する()
  + 2つの整数の足し算結果を取得する()
}

@enduml