@startuml 図書館システム-クラス図

skinparam classAttributeIconSize 0
hide circle

class 図書館システム {
 -図書
 -予約カード

 +図書を借りる()
 +予約カードを作成する()
}

class 会員 {
 -学生証/職員証
 -学生番号/職員番号
 -会員番号
 -借りている図書
 -借りられる図書の種類
 -借りられる図書の上限冊数
 -メールアドレス

 +会員番号を取得する()
 +借りている図書を返却する()
}

class 図書 {
 -管理番号
 -貸出期間
 -貸し出し履歴

 +貸し出し履歴の記録()
 +貸し出し履歴の閲覧()
}

@enduml