@startuml 図書館システム-クラス図2

skinparam classAttributeIconSize 0
hide circle

class 会員 {
 -学生証/職員証
 -学生番号/職員番号
 -会員番号
 -借りている図書
 -借りられる図書の種類
 -借りられる図書の上限冊数
 -メールアドレス

 +会員番号を取得する()
 +借りている図書を返却する()
}

@enduml