@startuml .

class 注文管理システム{
    - 注文ID
    - 合計金額
    - 注文日
    - 商品ID
    - 顧客ID
    - 注文履歴

    + 商品を登録する()
    + 商品を更新する()
    + 商品を削除する()
    + 返金する()
    + 商品を配送する()
    + アカウントを管理する()
}

class 在庫管理システム{
    + 在庫を補充する()
    + 商品を参照する()
    + 在庫を廃棄する()
}

class 販売システム{
    + ログインする()
    + ログアウトする()
    + 商品を参照する()
    + 商品を購入する()
    + 注文履歴を確認する()
    + 注文をキャンセルする()
    + 商品を返品する()
}

@enduml