@startuml .
skinparam classAttributeIconSize 0

class Customer{
    - customerID: String
    - name: String
    - address: String
    - phoneNumber: String
    - mailAddress: String
    - password: String

    + createCustomorAccount()
    + viewCustomorAccount()
    + updateCustomorAccount()
    + login()
    + logout()
    + withdraw()
}

class Admin {
    - adminID: String
    - name: String
    - password: String
    - role: String

    + login()
    + logout()
}

class SystemAdmin {
    - systemAdminID: String
    - name: String
    - password: String
    - role: String

    + createSystemAdminAccount()
    + viewCustomorAccount()
    + changeRole()
    + login()
    + logout()
    + deactivateAccount()
}

class OrderStockAdmin {
    - adminID: String
    - name: String
    - password: String
    - role: String

    + login()
    + logout()
    + prepareShipment()
    + shipProdct()
}

class CustomerSupport {
    - adminID: String
    - name: String
    - password: String
    - role: String

    + login()
    + logout()
}

class Order {
    - orderID: String
    - customorID: String
    - orderDate: Date
    - shippingFee: int
    - paymentStatus: {1:success, 2:failure}

    + createOrder()
    + viewOrder()
    + updateOrder()
}

class OrderDetail {
    - orderDetailID: String
    - orderID: String
    - goodsID: String
    - quantity: int
    - status: {1:paid, 2:shipped, 3:cancelled}

    + updateStatus()
}

class Invoice {
    - invoiceID: String
    - customorID: String
    - orderID: String
    - goodsID: String

    + createInvoice()
}

class Cart {
    - customorID: String
    - goodsID: String
    - quantity: int

    + createCart()
    + viewCart()
    + deleteCart()
    + updateQuantity()
}

class Goods {
    - goodsID: String
    - goodsName: String
    - description: String
    - price: int
    - stock: int
    - image1ID: String
    - image2ID: String
    - image3ID: String
    - image4ID: String

    + createGoods()
    + updateGoods()
    + viewGoods()
    + deleteGoods()
}


Customer "1" o-- "0..*" Cart

Cart "1" o-- "1" Goods

Customer "1" o-- "0..*" Order

Order "1" o-- "1..*" OrderDetail

OrderDetail "1" o-- "1" Goods

Invoice "1" o-- "1" OrderDetail

Admin <|-- SystemAdmin

Admin <|-- OrderStockAdmin

Admin <|-- CustomerSupport

@enduml