@startuml .
skinparam classAttributeIconSize 0

class 顧客{
    - 顧客ID: String
    - 名前: String
    - 住所: String
    - 電話番号: String
    - メールアドレス: String
    - パスワード: String

    + 顧客アカウントを作成する()
    + 顧客情報を参照する()
    + 顧客情報を変更する()
    + ログインする()
    + ログアウトする()
    + 退会する()
}

class 管理者 {
    - 管理者ID: String
    - 名前: String
    - パスワード: String
    - 権限: String

    + ログインする()
    + ログアウトする()
}

class システム管理者 {
    - 管理者ID: String
    - 名前: String
    - パスワード: String
    - 権限: String

    + 管理者サイトアカウントを作成する()
    + アカウントを参照する()
    + アカウント権限を変更する()
    + ログインする()
    + ログアウトする()
    + アカウントを停止する()
}

class 注文在庫管理者 {
    - 管理者ID: String
    - 名前: String
    - パスワード: String
    - 権限: String

    + ログインする()
    + ログアウトする()
    + 出荷準備をする()
    + 商品を発送する()
}

class カスタマーサポート {
    - 管理者ID: String
    - 名前: String
    - パスワード: String
    - 権限: String

    + ログインする()
    + ログアウトする()
}

class 注文 {
    - 注文ID: String
    - 顧客ID: String
    - 注文日: Data
    - 送料: int
    - 決済情報: {1:成功, 2:失敗}

    + 注文を作成する()
    + 注文情報を参照する()
    + 注文情報を変更する()
}

class 注文詳細 {
    - 注文詳細ID: String
    - 注文ID: String
    - 商品ID: String
    - 注文数: int
    - ステータス: {1:入金済, 2:出荷済, 3:キャンセル}

    + ステータスを変更する()
}

class 伝票 {
    - 伝票ID: String
    - 顧客ID: String
    - 注文ID: String
    - 商品ID: String

    + 伝票を発行する()
}

class カート {
    - 顧客ID: String
    - 商品ID: String
    - 商品数: int

    + カートを作成する()
    + カートの商品を参照する()
    + カートを削除する()
    + 商品数を変更する()
}

class 商品 {
    - 商品ID: String
    - 商品名: String
    - 説明: String
    - 価格: int
    - 在庫数: int
    - 画像1ID: String
    - 画像2ID: String
    - 画像3ID: String
    - 画像4ID: String

    + 商品情報を登録する()
    + 商品情報を更新する()
    + 商品情報を参照する()
    + 商品情報を削除する()
}


顧客 "1" o-- "0..*" カート

カート "1" o-- "1" 商品

顧客 "1" o-- "0..*" 注文

注文 "1" o-- "1..*" 注文詳細

注文詳細 "1" o-- "1" 商品

伝票 "1" o-- "1" 注文詳細

管理者 "1" <|-- "1..*" システム管理者

管理者 "1" <|-- "0..*" 注文在庫管理者

管理者 "1" <|-- "0..*" カスタマーサポート

@enduml