@startuml

title BB販売ドメインモデル
skinparam componentStyle rectangle
[顧客] o-- [顧客ID]
[顧客] o-- [名前]
[顧客] o-- [住所]
[顧客] o-- [電話番号]
[顧客] o-- [メールアドレス]
[顧客] o-- [パスワード]
[顧客] o-- [注文履歴]
[顧客] o-- [決済履歴]
[顧客] o-- [カート]

[注文データ] o-- [注文ID]
[注文データ] o-- [顧客ID]
[注文データ] o-- [商品ID]
[注文データ] o-- [注文日]
[注文データ] o-- [注文数]
[注文データ] o-- [送料]
[注文データ] o-- [決済情報]

[決済情報] <|-- [成功]
[決済情報] <|-- [失敗]

[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [価格]
[商品] o-- [在庫数]

@enduml