@startuml

title BB販売ドメインモデル
skinparam componentStyle rectangle
[顧客] o-- [顧客ID]
[顧客] o-- [名前]
[顧客] o-- [住所]
[顧客] o-- [電話番号]
[顧客] o-- [メールアドレス]
[顧客] o-- [パスワード]
[顧客] o-- [注文履歴]
[顧客] o-- [カート]

[管理者] o-- [管理者ID]
[管理者] o-- [名前]
[管理者] o-- [パスワード]
[管理者] o-- [権限]

[権限] <|-- [システム管理]
[権限] <|-- [注文在庫管理]
[権限] <|-- [カスタマーサポート]

' 顧客に表示される情報
[注文履歴] o-- [顧客ID]
[注文履歴] o-- [注文ID]
[注文履歴] o-- [注文日]
[注文履歴] o-- [商品ID]
[注文履歴] o-- [商品名]
[注文履歴] o-- [ステータス]

[ステータス] <|-- [入金済]
[ステータス] <|-- [出荷準備中]
[ステータス] <|-- [出荷済]
[ステータス] <|-- [到着済]
[ステータス] <|-- [キャンセル]


[カート] o-- [商品ID]
[カート] o-- [商品名]
[カート] o-- [商品価格]
' 画像は商品に設定された画像1
[カート] o-- [画像1]
[カート] o-- [商品の数量]

' 注文在庫管理者に表示される情報
[注文データ] o-- [注文ID]
[注文データ] o-- [顧客ID]
[注文データ] o-- [商品ID]
[注文データ] o-- [注文日]
[注文データ] o-- [注文数]
[注文データ] o-- [送料]
[注文データ] o-- [決済情報]

' 配送用の伝票に印字される情報
[伝票] o-- [注文ID]
[伝票] o-- [商品ID]
[伝票] o-- [商品名]
[伝票] o-- [顧客名]
[伝票] o-- [住所]
[伝票] o-- [電話番号]

[決済情報] <|-- [成功]
[決済情報] <|-- [失敗]

' 商品ページ用
[商品] o-- [商品ID]
[商品] o-- [商品名]
[商品] o-- [説明]
[商品] o-- [価格]
[商品] o-- [在庫数]
' 画像1はNOT NULL
[商品] o-- [画像1]
[商品] o-- [画像2]
[商品] o-- [画像3]
[商品] o-- [画像4]

@enduml