@startuml .

hide footbox
skinparam BoundaryBackgroundColor #D5E8D4
skinparam ControlBackgroundColor #F8CECC
skinparam EntityBackgroundColor #DAE8FC

actor 注文在庫管理者 as User
boundary stockMenu.jsp as Menu
boundary sendReady.jsp as Sending
boundary OrderList.jsp as List
control SendReady.java as Display
control SendReadyProcess.java as Process
' entity BB販売システム as System
entity OrderDetail.java as OrderDetailDB
entity Order.java as OrderDB

User -> Menu: 「出荷準備」を選択

activate Menu
Menu -> Display

activate Display
Display -> OrderDB: 出荷準備対象の注文データを取得()

activate OrderDB
OrderDB --> Display: 注文データ一覧
deactivate OrderDB

Display -> Sending: 出荷準備画面表示()
deactivate Menu
deactivate Display

activate Sending
User -> Sending: 「出荷準備を完了する」を選択
Sending -> Process: 

activate Process
Process -> OrderDetailDB: ステータスを「集荷待ち」に変更()

activate OrderDetailDB
OrderDetailDB --> Process: 処理結果
deactivate OrderDetailDB

Process -> List: 注文データ一覧画面を表示()
deactivate Process

activate List
deactivate Sending

@enduml