@startuml
hide footbox
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor  #F8CECC
skinparam entityBackgroundColor   #DAE8FC

actor 顧客 as user
boundary 商品詳細画面 as B1
boundary 商品一覧画面 as B2
boundary カート一覧画面 as B3
control 認証 as C1
control メッセージ表示 as C2
entity BB管理システム as E

user -> B1: 「カートに追加」を選択
activate B1

B1 -> C1: 商品情報を送信()
activate C1
C1 -> E: 商品情報の確認・保存()
deactivate C1
activate E

alt 商品情報に不備あり
    E -> C2: 認証失敗
    activate C2
    C2 -> B1: 「カートへの追加に失敗しました」バナー表示
    deactivate C1
else 商品が削除済み
    E -> C2: 認証失敗
    C2 -> B2: 「この商品は販売不可の商品です」バナー表示
    activate B2
    deactivate C1
    deactivate B2
    deactivate C2

end

alt ユーザー未ログイン
    B1 -> C1: 商品情報を送信()
    activate C1
    C1 -> C1: トークン付き商品データをcookie保存()
    C1 -> B1: 「カートに追加しました」バナー表示
    C1 -> B3: 商品情報送信
    activate B3
    deactivate C1
    deactivate B3

end

E -> C2: カート追加成功
activate C2
C2 -> B1: 「カートに追加しました」バナー表示
deactivate C2
E --> B3: 商品情報送信
activate B3
deactivate B3
deactivate E
deactivate C1
deactivate B1


@enduml