@startuml
hide footbox
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor  #F8CECC
skinparam entityBackgroundColor   #DAE8FC

actor "customer" as user
boundary "goodsDetail.html" as B1
boundary "goodsList.html" as B2
' control 認証 as C1
' control メッセージ表示 as C2
control "addGoods.jsp" as C3
entity "goods.java" as E1
entity "cart.java" as E2

user -> B1: 「カートに追加」を選択()
activate B1

B1 -> C3: 商品情報を送信()
activate C3
' C3 -> E1: 商品情報の確認()
C3 -> E1: getGoodsInfo()
activate E1
E1 --> C3: 在庫情報


alt ユーザー未ログイン
    ' C3 -> C3: トークン付き商品データをcookie保存()
    C3 -> C3: setGoodsDataInCookie()
    C3 -> B1: 「カートに追加しました」バナー表示

end

alt 在庫なし
    E1 --> C3: 在庫数０
    
    C3 -> B1: 「この商品は在庫がありません」バナー表示
else 商品が削除済み
    E1 --> C3: 該当の商品なし
    C3 -> B2: 「この商品は販売不可の商品です」バナー表示
    activate B2
    deactivate B2

end


E1 --> C3: 商品情報
deactivate E1
' C3 -> E2: カートに追加()
C3 -> E2: setGoodsInfo()
activate E2
E2 --> C3
deactivate E2

C3 -> B1: 「カートに追加しました」バナー表示
deactivate C3


@enduml