@startuml BB注文管理システムユースケース図
left to right direction
actor システム管理者

actor 顧客

actor カスタマーサポート

actor 在庫管理業者


rectangle BBシステム {
  usecase "商品を登録する" as UC1
  usecase "商品を更新する" as UC2
  usecase "商品を削除する" as UC3
  usecase "返金する" as UC4
  usecase "商品を配送する" as UC5
  usecase "アカウントを管理する" as UC6

  usecase "ログインする" as UC7
  usecase "ログアウトする" as UC8
  usecase "商品を参照する" as UC9
  usecase "商品を購入する" as UC10
  usecase "注文履歴を確認する" as UC11
  usecase "注文をキャンセルする" as UC12
  usecase "商品を返品する" as UC13

  usecase "在庫を補充する" as UC14
  usecase "在庫を参照する" as UC15
  usecase "在庫を廃棄する" as UC16
}

システム管理者 --> UC1
システム管理者 --> UC2
システム管理者 --> UC3
システム管理者 --> UC5
システム管理者 --> UC6
システム管理者 --> UC12

顧客 --> UC7
顧客 --> UC8
顧客 --> UC9
顧客 --> UC10
顧客 --> UC11
顧客 --> UC12
顧客 --> UC13

カスタマーサポート --> UC4
カスタマーサポート --> UC13

在庫管理業者 --> UC14
在庫管理業者 --> UC15
在庫管理業者 --> UC16
@enduml
