@startuml BB注文管理システムユースケース図
left to right direction
actor 管理者

rectangle 注文管理システム {
  usecase "商品を登録する" as UC1
  usecase "商品を更新する" as UC2
  usecase "商品を削除する" as UC3
  usecase "返金する" as UC4
  usecase "商品を配送する" as UC5
  usecase "アカウントを管理する" as UC6

}

管理者 --> UC1
管理者 --> UC2
管理者 --> UC3
管理者 --> UC4
管理者 --> UC5
管理者 --> UC6
@enduml
