@startuml BB注文管理システムユースケース図
left to right direction
actor 顧客 as U

actor システム管理者 as M

actor 商品管理者 as OM

actor カスタマーサポート as CS

actor 在庫管理者 as SM

rectangle BBサイト {
  usecase "顧客アカウント作成" as UC1
  usecase "顧客情報を変更する" as UC2
  usecase "ログインする" as UC3
  usecase "ログアウトする" as UC4
  usecase "商品を参照する" as UC5
  usecase "カートに追加する" as UC6
  usecase "カートを閲覧する" as UC7
  usecase "カートから削除する" as UC8
  usecase "商品を購入する" as UC9
  usecase "注文履歴を確認する" as UC10
  usecase "注文をキャンセルする" as UC11
  usecase "商品を返品する" as UC12
}

rectangle 注文・在庫管理サイト {
  usecase "管理サイトアカウント作成" as UC13
  usecase "アカウントの閲覧" as UC14
  usecase "アカウント権限の変更" as UC15
  usecase "アカウントの停止" as UC16
  usecase "商品項目を登録する" as UC17
  usecase "商品項目を更新する" as UC18
  usecase "商品項目を削除する" as UC19
  usecase "返金する" as UC21
  usecase "返品を受け付ける" as UC22
  usecase "注文履歴を確認する" as UC23
  usecase "決済履歴を確認する" as UC24
  usecase "在庫を補充する" as UC25
  usecase "在庫を参照する" as UC26
  usecase "在庫を廃棄する" as UC27
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6
U --> UC7
U --> UC8
U --> UC9
U --> UC10
U --> UC11
U --> UC12

M --> UC13
M --> UC14
M --> UC15
M --> UC16

OM --> UC17
OM --> UC18
OM --> UC19

CS --> UC21
CS --> UC22
CS --> UC23
CS --> UC24

SM --> UC25
SM --> UC26
SM --> UC27
@enduml